name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  release:
    uses: Avkroken/.github/.github/workflows/release-please.yml@main
    secrets:
      app-private-key: ${{ secrets.GAMNACKEN_PRIVATE_KEY }}
